### ISSUE TITLE
Resolution of recorded images in Tangra

### ISSUE THREAD

**Issue by MarekZawilski** [hpavlov/tangra3#4]
When you make recordings during occultation observations and set a resolution image given by your camera, especially with binning=2, please remember: the final resolution will be appear in the Tangra window with the final value, i.e. the rectangle will be 2x smaller with binning=2.
However, with such setting you obtain better quality of starfield and a faster transmission (higher fps) to your hard drive.
Tell something about you experience, please!

**Comment by hpavlov** [comment]
Hi @MarekZawilski , as this appears to be a question rather than a bug report or a feature request, I am thinking of closing this issue. Let me know if you are okay with that?
